 error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [311 lines of output]
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/92/81/65ae90d584a73ca976d8f1eb83e2f58447a4055a9fb3ae69b28721070bdf/wheel-0.45.0-py3-none-any.whl.metadata
        Using cached wheel-0.45.0-py3-none-any.whl.metadata (2.3 kB)
      Collecting setuptools
        Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/fe/df/88ccbee85aefbca071db004fdc8f8d2507d55d5a9dc27ebb93c92edb1bd8/setuptools-75.5.0-py3-none-any.whl.metadata
        Using cached setuptools-75.5.0-py3-none-any.whl.metadata (6.8 kB)
      Collecting cython>=0.28.0
        Obtaining dependency information for cython>=0.28.0 from https://files.pythonhosted.org/packages/fd/10/236fcc0306f85a2db1b8bc147aea714b66a2f27bac4d9e09e5b2c5d5dcca/Cython-3.0.11-cp311-cp311-win_amd64.whl.metadata
        Using cached Cython-3.0.11-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
      Collecting numpy<v1.20.0
        Using cached numpy-1.19.5.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [274 lines of output]
        setup.py:67: RuntimeWarning: NumPy 1.19.5 may not yet support Python 3.11.
          warnings.warn(
        Running from numpy source directory.
        setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
          run_build = parse_setuppy_commands()
        Processing numpy/random\_bounded_integers.pxd.in
        Processing numpy/random\bit_generator.pyx
        Processing numpy/random\mtrand.pyx
        Processing numpy/random\_bounded_integers.pyx.in
        Processing numpy/random\_common.pyx
        Processing numpy/random\_generator.pyx
        Processing numpy/random\_mt19937.pyx
        Processing numpy/random\_pcg64.pyx
        Processing numpy/random\_philox.pyx
        Processing numpy/random\_sfc64.pyx
        Cythonizing sources
        blas_opt_info:
        blas_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        blis_info:
          libraries blis not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        openblas_info:
          libraries openblas not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
        Could not locate executable ifort
        Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Could not locate executable DF
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
          NOT AVAILABLE

        atlas_3_10_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries tatlas not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        atlas_3_10_blas_info:
          libraries satlas not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        atlas_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        atlas_blas_info:
          libraries f77blas,cblas,atlas not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        accelerate_info:
          NOT AVAILABLE

        C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\system_info.py:1914: UserWarning:
            Optimized (vendor) Blas libraries are not found.
            Falls back to netlib Blas library which has worse performance.
            A better performance should be easily gained by switching
            Blas library.
          if self._calc_info(blas):
        blas_info:
          libraries blas not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\system_info.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [blas]) or by setting
            the BLAS environment variable.
          if self._calc_info(blas):
        blas_src_info:
          NOT AVAILABLE

        C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\system_info.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [blas_src]) or by setting
            the BLAS_SRC environment variable.
          if self._calc_info(blas):
          NOT AVAILABLE

        non-existing path in 'numpy\\distutils': 'site.cfg'
        lapack_opt_info:
        lapack_mkl_info:
          libraries mkl_rt not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        openblas_lapack_info:
          libraries openblas not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        openblas_clapack_info:
          libraries openblas,lapack not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        flame_info:
          libraries flame not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        atlas_3_10_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Users\irist\OneDrive\デスクトップ\myvenv\lib
          libraries tatlas,tatlas not found in C:\Users\irist\OneDrive\デスクトップ\myvenv\lib
          libraries lapack_atlas not found in C:\
          libraries tatlas,tatlas not found in C:\
        <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
          NOT AVAILABLE

        atlas_3_10_info:
          libraries lapack_atlas not found in C:\Users\irist\OneDrive\デスクトップ\myvenv\lib
          libraries satlas,satlas not found in C:\Users\irist\OneDrive\デスクトップ\myvenv\lib
          libraries lapack_atlas not found in C:\
          libraries satlas,satlas not found in C:\
        <class 'numpy.distutils.system_info.atlas_3_10_info'>
          NOT AVAILABLE

        atlas_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Users\irist\OneDrive\デスクトップ\myvenv\lib
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\irist\OneDrive\デスクトップ\myvenv\lib
          libraries lapack_atlas not found in C:\
          libraries ptf77blas,ptcblas,atlas not found in C:\
        <class 'numpy.distutils.system_info.atlas_threads_info'>
          NOT AVAILABLE

        atlas_info:
          libraries lapack_atlas not found in C:\Users\irist\OneDrive\デスクトップ\myvenv\lib
          libraries f77blas,cblas,atlas not found in C:\Users\irist\OneDrive\デスクトップ\myvenv\lib
          libraries lapack_atlas not found in C:\
          libraries f77blas,cblas,atlas not found in C:\
        <class 'numpy.distutils.system_info.atlas_info'>
          NOT AVAILABLE

        lapack_info:
          libraries lapack not found in ['C:\\Users\\irist\\OneDrive\\デスクトップ\\myvenv\\lib', 'C:\\']
          NOT AVAILABLE

        C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\system_info.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        lapack_src_info:
          NOT AVAILABLE

        C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\system_info.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
          NOT AVAILABLE

        numpy_linalg_lapack_lite:
          FOUND:
            language = c
            define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

        C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
          warnings.warn(msg)
        running dist_info
        running build_src
        build_src
        building py_modules sources
        creating build
        creating build\src.win-amd64-3.11
        creating build\src.win-amd64-3.11\numpy
        creating build\src.win-amd64-3.11\numpy\distutils
        building library "npymath" sources
        Traceback (most recent call last):
          File "C:\Users\irist\OneDrive\デスクトップ\myvenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>     
            main()
          File "C:\Users\irist\OneDrive\デスクトップ\myvenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\OneDrive\デスクトップ\myvenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\build_meta.py", line 249, in run_setup
            self).run_setup(setup_script=setup_script)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 508, in <module>
            setup_package()
          File "setup.py", line 500, in setup_package
            setup(**metadata)
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\core.py", line 169, in setup       
            return old_setup(**new_attr)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\__init__.py", line 165, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
            dist.run_commands()
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands     
            self.run_command(cmd)
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command      
            cmd_obj.run()
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 31, in run
            egg_info.run()
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\command\egg_info.py", line 24, in run
            self.run_command("build_src")
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command       
            self.distribution.run_command(command)
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command      
            cmd_obj.run()
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\command\build_src.py", line 144, in run
            self.build_sources()
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\command\build_src.py", line 155, in build_sources
            self.build_library_sources(*libname_info)
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\command\build_src.py", line 288, in build_library_sources
            sources = self.generate_sources(sources, (lib_name, build_info))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\command\build_src.py", line 378, in generate_sources
            source = func(extension, build_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "numpy\core\setup.py", line 658, in get_mathlib_info
            st = config_cmd.try_link('int main(void) { return 0;}')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 243, in try_link
            self._link(body, headers, include_dirs,
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\command\config.py", line 162, in _link
            return self._wrap_method(old_config._link, lang,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\command\config.py", line 96, in _wrap_method
            ret = mth(*((self,)+args))
                  ^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 137, in _link  
            (src, obj) = self._compile(body, headers, include_dirs, lang)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\command\config.py", line 105, in _compile
            src, obj = self._wrap_method(old_config._compile, lang,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\command\config.py", line 96, in _wrap_method
            ret = mth(*((self,)+args))
                  ^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
            self.compiler.compile([src], include_dirs=include_dirs)
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 401, in compile 
            self.spawn(args)
          File "C:\Users\irist\AppData\Local\Temp\pip-build-env-jyus0kzn\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 505, in spawn   
            return super().spawn(cmd, env=env)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\irist\AppData\Local\Temp\pip-install-mpwz5u2x\numpy_79770ec213a04f72ac766055e539bdce\numpy\distutils\ccompiler.py", line 90, in <lambda>
            m = lambda self, *args, **kw: func(self, *args, **kw)
                                          ^^^^^^^^^^^^^^^^^^^^^^^
        TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.

      [notice] A new release of pip is available: 23.2.1 -> 24.3.1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.